const fs = require('fs');
const path = require('path');

const backendUrl = process.env.BACKEND_URL || 'http://127.0.0.1:8000';
const out = `// Auto-generated by set_backend_url.js\nexport const BACKEND_URL = '${backendUrl}';\n`;
const target = path.join(__dirname, 'src', 'config.js');
fs.writeFileSync(target, out);
console.log('Wrote', target, '->', backendUrl);
